-- Summary
-- Stores the available contract types used by the application.
-- Each contract type has a unique name and active flag indicating whether
-- it is currently available for use.


-- Changed By History
-- Record the person or process responsible for each change below.
-- Date         | Changed by | Description
-- 27/08/2026   | Steve S    | Initial creation of the contract type table to store the available contract types used by the application.   

CREATE TABLE job_contract_type (
    contract_type_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    contract_type    VARCHAR2(50) NOT NULL,
    active_flag      CHAR(1) DEFAULT 'Y' NOT NULL,

    CONSTRAINT job_contract_type_pk PRIMARY KEY (contract_type_id),
    CONSTRAINT job_contract_type_uk UNIQUE (contract_type),
    CONSTRAINT job_contract_type_active_ck
        CHECK (active_flag IN ('Y','N'))
);