-- Summary
-- Stores job opportunities, company details, compensation, work arrangement,
-- application status, important dates, contact information, and notes.


-- Changed By History
-- Record the person or process responsible for each change below.
-- Date         | Changed by | Description
-- 27/08/2026   | Steve S    | Initial creation of the jobs table to store job opportunities and related information.  

CREATE TABLE jobs (
    job_id          NUMBER GENERATED BY DEFAULT AS IDENTITY,
    job_title       VARCHAR2(200) NOT NULL,
    company_name    VARCHAR2(200) NOT NULL,
    location        VARCHAR2(200),
    salary_min      NUMBER,
    salary_max      NUMBER,
    contract_type   VARCHAR2(50),
    working_type    VARCHAR2(50),
    status          VARCHAR2(50) DEFAULT 'Found',
    date_found      DATE DEFAULT SYSDATE,
    date_applied    DATE,
    closing_date    DATE,
    job_url         VARCHAR2(1000),
    recruiter       VARCHAR2(200),
    notes           VARCHAR2(4000),

    CONSTRAINT jobs_pk PRIMARY KEY (job_id)
);