-- Summary
-- Stores the available job status values used by the application.
-- Each status has a unique name, display order, and active flag indicating
-- whether it is currently available for use.


-- Changed By History
-- Record the person or process responsible for each change below.
-- Date         | Changed by | Description
-- 27/08/2026   | Steve S    | Initial creation of the jobs status table to store the available job status values used by the application.   

DROP TABLE job_status; 

CREATE TABLE job_status (
    status_id       NUMBER GENERATED BY DEFAULT AS IDENTITY,
    status_name     VARCHAR2(50) NOT NULL,
    display_order   NUMBER,
    active_flag     CHAR(1) DEFAULT 'Y' NOT NULL,

    CONSTRAINT job_status_pk PRIMARY KEY (status_id),
    CONSTRAINT job_status_uk UNIQUE (status_name),
    CONSTRAINT job_status_active_ck CHECK (active_flag IN ('Y','N'))
);