-- Summary
-- Stores the available working types used by the application.
-- Each working type has a unique name and active flag indicating whether
-- it is currently available for use.


-- Changed By History
-- Record the person or process responsible for each change below.
-- Date         | Changed by | Description
-- 27/08/2026   | Steve S    | Initial creation of the working type table to store the available working types used by the application.   

CREATE TABLE working_type (
    working_type_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    working_type    VARCHAR2(50) NOT NULL,
    active_flag     CHAR(1) DEFAULT 'Y' NOT NULL,

    CONSTRAINT job_working_type_pk PRIMARY KEY (working_type_id),
    CONSTRAINT job_working_type_uk UNIQUE (working_type),
    CONSTRAINT job_working_type_active_ck
        CHECK (active_flag IN ('Y','N'))
);